CREATE DATABASE IF NOT EXISTS companydb;
USE companydb;
CREATE TABLE employee (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) DEFAULT NULL,
    salary INT(5) DEFAULT NULL,
    PRIMARY KEY (id)
);

DESCRIBE employee

INSERT INTO employee VALUES
(1, 'FRANK', 1000),
(2, 'PEPE', 1300),
(3, 'NEYMAR', 1700),
(4, 'CRISTIANO', 1600);
